### ISSUE TITLE
Cannot set unknown member 'System.Windows.Window.InputBindings

### ISSUE THREAD

**Issue by joshnoe** [markryd/XamlWatcher#2]
I'm getting the above error when making any changes to my xaml. Unfortunately, this is proprietary code and I can't post it here, but if there's anything I can do to help, just let me know.

Here's some tracing and a stack trace:
Getting context
Building holder
Updating instances of view
System.Windows.Markup.XamlParseException: 'Cannot set unknown member 'System.Windows.Window.InputBindings'.' Line number '10' and line position '4'. ---> System.Xaml.XamlObjectWriterException: 'Cannot set unknown member 'System.Windows.Window.InputBindings'.' Line number '10' and line position '4'.
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext)
   at XamlWatcher.WPF.Watcher.UpdateLiveInstancesOfTheView(Type type, XDocument holder, ParserContext context)
   at XamlWatcher.WPF.Watcher.ProcessView(XDocument xml, Type viewType)
   at XamlWatcher.WPF.Watcher.SetNewContent(String path)
   at XamlWatcher.WPF.Watcher.<>c__DisplayClass2.<watcher_Changed>b__1()

**Comment by markryd** [comment]
Thanks for the bug report. I've just pushed 1.0.26 up to Nuget which should fix this. Edited InputBindings won't live refresh due to the way XamlWatcher works, but just having them on the page won't crash now.
